[package]
authors = ["Joseph Livesey <joseph@semiotic.ai>"]
description = "DEPRECATED: Use alloy-erc20-full instead"
repository = "https://github.com/suchapalaver/erc20-rs"
name = "erc20-rs"
version = "0.3.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
alloy-erc20-full = "1.0"
